export const clinic = { name:'HealthFlow Clinic', tagline:'Care that moves with you.', description:'A modern multispecialty clinic with real-time appointment tracking and a calmer patient experience.', phone:'+1 (555) 014-2040', email:'hello@healthflowclinic.demo', address:'1200 Meridian Avenue, Suite 200, Austin, TX 78701', hours:['Mon–Fri · 8:00 AM–7:00 PM','Sat · 9:00 AM–2:00 PM','Sun · Closed'], stats:[['15+','Years experience'],['25k+','Patients served'],['98%','Patient satisfaction'],['4.9/5','Average care rating']] } as const;
export const services = ['General Medicine','Family Medicine','Pediatrics','Dermatology','ENT','Cardiology','Diabetes Care','Women’s Health','Men’s Health','Vaccinations','Preventive Care','Diagnostic Services'].map((name)=>({ slug:name.toLowerCase().replaceAll(' ','-').replaceAll('’',''), name }));
export const doctors = [
 {id:'maya-patel',name:'Dr. Maya Patel',role:'Internal Medicine',image:'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85',bio:'Thoughtful, evidence-based care for adults at every stage.',education:'MD, University of Michigan',experience:'15 years',languages:['English','Hindi','Spanish']},
 {id:'james-wilson',name:'Dr. James Wilson',role:'Cardiology',image:'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=900&q=85',bio:'Complex heart health translated into calm, practical next steps.',education:'MD, Johns Hopkins University',experience:'18 years',languages:['English']},
 {id:'sofia-ramirez',name:'Dr. Sofia Ramirez',role:'Pediatrics',image:'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=900&q=85',bio:'A reassuring space where children and parents feel heard.',education:'MD, UT Southwestern',experience:'11 years',languages:['English','Spanish']},
 {id:'noah-chen',name:'Dr. Noah Chen',role:'Dermatology',image:'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=900&q=85',bio:'Clinical precision with a conservative, patient-first approach.',education:'MD, Stanford University',experience:'12 years',languages:['English','Mandarin']}
];
export const faqs = [['How does live queue tracking work?','After booking or checking in, you receive an appointment number. Track your position, patients ahead and the latest estimated wait in real time.'],['Can I book online?','Yes. Choose a service, doctor, date and time, then add your contact details.'],['What if I am running late?','Call our front desk as soon as possible so the team can advise whether your place can be held.'],['Is this production-ready for real patient data?','The UI and Supabase architecture are ready for integration. Before launch, complete HIPAA/security review, legal policies, audit logging and clinical workflows.']];
